# Generated by Django 2.2.17 on 2020-11-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RbaFile',
        ),
    ]
